; ODR-DabMOd Konfiguration 
[remotecontrol] 
telnet=0
telnetport=2121 
zmqctrl=0

[log] 
syslog=0
filelog=0 
filename=/dev/stderr 

[input] 
transport=edi
source=tcp://hurley:13000
#loop=1

[modulator] 
gainmode=var
mode=l 
digital_gain=0.8
rate=2048000
dac_clk_rate=0

[firfilter] 
enabled=0
filtertapsfile=filtertaps.txt 

[output] 
#output=uhd 
output=soapysdr

[soapyoutput]
device=
master_clock_rate=32768000
txgain=23
channel=5A


[fileoutput] 
filename=/dev/stdout 

[uhdoutput] 
device= 
master_clock rate=32768000
type=b100 
txgain=2
channel=5A 
refclk source=internal 
behaviour_refclk_lock_lost=ignore
max_gps_holdover_time=0

 
[zmqoutput] 
listen=tcp://*:54001
socket_type=pub 

#[delaymanagement] 
#synchronous=0
#mutenotimestamps=0 
#offset=O.002


