[remotecontrol]
telnet=1
telnetport=2121
zmqctrl=1
zmqctrlendpoint=tcp://127.0.0.1:9400

[input]
transport=zeromq
source=tcp://localhost:9100
max_frames_queued=1000

[modulator]
gainmode=var
digital_gain=0.8
#rate=2048000
rate=4096000
rate=8192000

[cfr]
enable=1
clip=50.0
error_clip=0.1

[firfilter]
enable=1
enabled=1

[poly]
enabled=0
polycoeffile=polyCoefs

[output]
output=soapysdr

[soapyoutput]
device=driver=hackrf
master_clock_rate=32768000
txgain=43
channel=5A
bandwidth=1750000

#[delaymanagement]
#synchronous=0
#mutenotimestamps=0
#offset=0.002
#[tii]
#enable=0
#comb=1
#pattern=11
#old_variant=0

